import { VERSION, LAYERS, LIBRARY, DEFAULT_HDL, clone, clamp, center, SpatialIndex, History, createDemo, compileHDL, evaluateLogic, orderedGates, simulate, quickRoute, analyzeTiming, checkDesign, designStats, synthesizeInto, validateProject, logicToHDL, validateLogic, exportDEF, importDEFPlacement } from './core.js';
import { LayoutRenderer, buildLayoutScene } from './renderer.js';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = (name,extra='') => `<svg class="icon ${extra}"><use href="#i-${name}"/></svg>`;
const fmt = (n,d=0) => Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const STORAGE_KEY='silicore:project:v1';
// randomUUID is secure-context-only; getRandomValues also works on an opaque/file origin.
function newID() {
  if(typeof crypto.randomUUID==='function') return crypto.randomUUID();
  const bytes=crypto.getRandomValues(new Uint8Array(16));
  bytes[6]=(bytes[6]&15)|64; bytes[8]=(bytes[8]&63)|128;
  const hex=[...bytes].map(v=>v.toString(16).padStart(2,'0')).join('');
  return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
}
let model=createDemo(),restoreMessage='',draft='';
try {const saved=localStorage.getItem(STORAGE_KEY);if(saved){model=validateProject(JSON.parse(saved));restoreMessage='Restored your local workspace.';}draft=localStorage.getItem('silicore:hdl-draft')||model.hdl;}catch(e){restoreMessage=`Local workspace was not restored: ${e.message}`;draft=model.hdl;}
const state={view:'layout',mode:'layout',tool:'select',leftTab:'hierarchy',bottom:'console',layers:clone(LAYERS),selection:new Set(),hover:null,selectedNet:null,schematicSelection:null,inputs:{},snap:true,cellLabels:false,routeOpacity:.29,expanded:new Set(['root','memories']),measure:null,pointer:null,routeStart:null,wireStart:null,busy:false,timing:analyzeTiming(model),checks:checkDesign(model),timingStale:false,checksStale:false,simulation:simulate(model.logic),cursor:0,logs:[],flow:{import:'done',place:'done',route:'preview',timing:'estimated',check:'done'},revision:model.revision||0};
const history=new History(),spatial=new SpatialIndex();spatial.rebuild(model.cells);
let storageWarningShown=false,autosaveTimer,uiFrame=0,commandHistory=[],commandHistoryIndex=0,schematicGeometry=null;
class WorkerBridge {
  constructor(){this.next=0;this.pending=new Map();this.start();}
  start(){
    try{
      this.worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});
      this.worker.onmessage=({data})=>{
        const pending=this.pending.get(data.id);if(!pending)return;
        if(data.progress!==undefined){pending.progress?.(data.progress);return;}
        this.pending.delete(data.id);clearTimeout(pending.timer);
        if(data.error){const error=new Error(data.error.message);Object.assign(error,data.error);pending.reject(error);}
        else pending.resolve(data);
      };
      this.worker.onerror=event=>{event.preventDefault();this.abort(new Error(event.message||'Worker failure'));};
      this.error=null;
    }catch(error){this.worker=null;this.error=error;}
  }
  abort(error){
    // A timed-out CPU task must actually stop, not just lose its awaiting promise.
    this.worker?.terminate();this.worker=null;this.error=error;
    for(const pending of this.pending.values()){clearTimeout(pending.timer);pending.reject(error);}this.pending.clear();
  }
  run(type,payload,progress){
    if(!this.worker)this.start();
    if(!this.worker)return Promise.reject(new Error(`Worker unavailable: ${this.error?.message}. Serve the project over localhost.`));
    const id=++this.next;
    return new Promise((resolve,reject)=>{
      const timer=setTimeout(()=>this.abort(new Error(`${type} exceeded its 60-second safety limit; the worker was terminated`)),60000);
      this.pending.set(id,{resolve,reject,progress,timer});
      try{this.worker.postMessage({id,type,payload,revision:state.revision});}catch(error){this.pending.delete(id);clearTimeout(timer);reject(error);}
    });
  }
}
const engine=new WorkerBridge();
const renderer=new LayoutRenderer($('#layoutCanvas'),$('#interaction'),(backend,error)=>{ $('#engineStatus').textContent=`${backend} accelerated${backend==='WebGPU'?'':' fallback'}`;if(backend!=='WebGPU')$('#engineStatus').textContent='Canvas 2D fallback';log(backend==='WebGPU'?'success':'info',backend==='WebGPU'?'WebGPU ready · instanced geometry · retained buffers':`Canvas 2D renderer active${error?` (${error})`:''}`); });
renderer.onOverlay=drawOverlay;

function log(kind,message){const time=new Date().toLocaleTimeString('en-GB',{hour12:false});state.logs.push({time,kind,message});if(state.logs.length>400)state.logs.shift();renderLogs();}
function renderLogs(){const labels={success:'OK',info:'INFO',warn:'WARN',error:'ERROR',command:'CMD'};$('#logs').innerHTML=state.logs.map(l=>`<div class="log ${l.kind}"><span class="log-time">${l.time}</span><span class="log-kind">${labels[l.kind]||'INFO'}</span><span class="log-text">${esc(l.message)}</span></div>`).join('');$('#logs').scrollTop=$('#logs').scrollHeight;}
function toast(message,error=false){const el=document.createElement('div');el.className=`toast${error?' error':''}`;el.textContent=message;const host=$('#toastContainer');while(host.children.length>=3)host.firstElementChild.remove();host.append(el);setTimeout(()=>el.remove(),4700);}
function status(message){$('#statusMessage').textContent=message;}
function setHint(message=''){$('#toolHint').hidden=!message;$('#toolHint').textContent=message;}
function queueSave(){clearTimeout(autosaveTimer);$('#saveStatus').innerHTML='<span class="small-dot"></span> Saving locally…';autosaveTimer=setTimeout(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(model));localStorage.setItem('silicore:hdl-draft',$('#hdlEditor').value);$('#saveStatus').innerHTML='<span class="small-dot"></span> Saved locally';}catch(e){$('#saveStatus').textContent=e.name==='QuotaExceededError'?'Local storage full':'Autosave unavailable';if(!storageWarningShown){storageWarningShown=true;log('warn',`Autosave unavailable: ${e.message}. Export the project to preserve changes.`);}}},500);}
function markChanged({reroute=false,edited=true}={}){state.revision++;model.revision=state.revision;if(reroute)model.nets=quickRoute(model);spatial.rebuild(model.cells);if(edited){state.timingStale=true;state.checksStale=true;}state.selection=new Set([...state.selection].filter(id=>model.cells.some(c=>c.id===id)));refreshScene();renderTree();renderInspector();renderFlow();renderReports();queueSave();}
function transact(label,fn,options={}){if(state.busy){toast('An implementation task is running. Editing resumes when it completes.');return false;}history.begin(model,label);try{fn();const changed=history.commit(model);if(changed){markChanged(options);status(label);}return changed;}catch(e){model=history.cancel()||model;spatial.rebuild(model.cells);refreshScene();renderTree();renderInspector();handleError(e);return false;}}
function handleError(error){console.error(error);log('error',error.message||String(error));toast(error.message||String(error),true);status(error.message||'Operation failed');}
function refreshScene(){renderer.setScene(buildLayoutScene(model,state.layers,{heatmap:state.mode==='congestion',cellLabels:state.cellLabels,routeOpacity:state.routeOpacity}));$('#visibleObjects').textContent=`${fmt(model.cells.length)} objects`;drawMinimap();}
function refreshAll(){spatial.rebuild(model.cells);refreshScene();renderTree();renderLayers();renderInspector();renderFlow();renderReports();syncEditor(model.hdl);if(state.view==='schematic')renderSchematic();if(state.view==='wave')renderWave();}
function selectCells(ids,{focus=false,extend=false}={}){if(!extend)state.selection.clear();for(const id of ids)state.selection.add(id);state.selectedNet=null;state.schematicSelection=null;renderInspector();renderTree();if(focus&&ids.length){setView('layout');const cells=model.cells.filter(c=>state.selection.has(c.id));if(cells.length){const minX=Math.min(...cells.map(c=>c.x)),minY=Math.min(...cells.map(c=>c.y)),maxX=Math.max(...cells.map(c=>c.x+c.w)),maxY=Math.max(...cells.map(c=>c.y+c.h));renderer.camera.fit({x:minX-90,y:minY-70,w:Math.max(180,maxX-minX+180),h:Math.max(140,maxY-minY+140)},70);}}renderer.invalidate();status(`${state.selection.size} object${state.selection.size===1?'':'s'} selected`);}
function selectedCells(){return model.cells.filter(c=>state.selection.has(c.id));}
function fit(){if(state.view==='schematic'){renderSchematic(true);return;}if(state.view!=='layout')setView('layout');renderer.resize();renderer.camera.fit({x:model.die.x-15,y:model.die.y-20,w:model.die.w+30,h:model.die.h+45},45);renderer.invalidate();drawMinimap();updateCameraStatus();}
function zoom(factor){if(state.view==='schematic'){const svg=$('#schematicSvg'),b=svg.viewBox.baseVal;svg.setAttribute('viewBox',`${b.x+(b.width-b.width/factor)/2} ${b.y+(b.height-b.height/factor)/2} ${b.width/factor} ${b.height/factor}`);return;}renderer.camera.zoomAt(renderer.camera.width/2,renderer.camera.height/2,factor);renderer.invalidate();drawMinimap();updateCameraStatus();}
function updateCameraStatus(){$('#zoomReadout').textContent=`${fmt(renderer.camera.zoom*100)}%`;$('#renderStats').textContent=`${fmt(renderer.primitiveCount)} primitives · ${renderer.frameMs.toFixed(1)} ms CPU`;}
function setTool(tool){if(state.view!=='layout')setView('layout');state.tool=tool;state.routeStart=null;state.pointer=null;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#interaction').style.cursor=tool==='hand'?'grab':['macro','route','measure'].includes(tool)?'crosshair':'default';const hints={route:'Select a source cell, then a destination cell',macro:'Drag to place a new macro block',measure:'Drag to measure a distance',hand:'Drag to pan · Scroll to zoom'};setHint(hints[tool]||'');status(`${tool[0].toUpperCase()+tool.slice(1)} tool`);renderer.invalidate();}
function setView(view){state.view=view;$$('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}View`));$$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.view===view));});$('#viewBreadcrumb').textContent={layout:'Floorplan',schematic:'control_unit',rtl:'rtl / control_unit.v',wave:'Simulation'}[view];$('#layoutModes').style.display=view==='layout'?'flex':'none';if(view==='layout'){renderer.resize();renderer.invalidate();}else if(view==='schematic')renderSchematic();else if(view==='wave')renderWave();else if(view==='rtl')requestAnimationFrame(()=>$('#hdlEditor').focus());renderInspector();}
function setBottom(tab){state.bottom=tab;document.body.classList.remove('console-hidden');$$('[data-bottom]').forEach(b=>b.classList.toggle('active',b.dataset.bottom===tab));$$('.bottom-content').forEach(el=>el.classList.toggle('active',el.id===`${tab}Body`));renderReports();}
function setMode(mode){state.mode=mode;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='timing'){setBottom('timing');if(state.timingStale)void runTask('timing');}refreshScene();}
function renderLayers(){const count=state.layers.filter(l=>l.visible).length;$('#layerCount').textContent=count;$('#layers').innerHTML=state.layers.map(l=>`<label class="layer-row" data-layerrow="${l.id}"><input type="checkbox" data-layer="${l.id}" ${l.visible?'checked':''} aria-label="Show ${esc(l.name)}"><span class="layer-swatch" style="background:${l.color}"></span><span class="layer-name">${l.name}</span><span class="layer-code">${/^M\d/.test(l.id)?l.id:l.id==='grid'?'ROW':l.id==='power'?'PG':''}</span></label>`).join('');}
function renderTree(){
  const filter=$('#treeSearch').value.trim().toLowerCase();const stats=designStats(model);
  const row=(label,id,type='chip',indent='',count='',expand=false)=>`<button class="tree-row ${indent} ${state.selection.has(id)?'active':''}" ${expand?`data-expand="${id}"`:`data-cell="${id}"`} role="treeitem"><svg class="icon tree-arrow ${state.expanded.has(id)?'open':''}" style="${expand?'':'visibility:hidden'}"><use href="#i-chevron"/></svg>${icon(type,type==='box'?'macro-icon':'')}<span class="tree-label">${esc(label)}</span><span class="tree-number">${count}</span></button>`;
  if(state.leftTab==='library'){ $('#tree').innerHTML=`<div class="lib-grid">${Object.entries(LIBRARY).filter(([t])=>!['SLICE','LAND','LOR','LNOT','EQ','NE','SUB'].includes(t)).map(([type,lib])=>`<button class="library-cell" data-insert="${type}">${icon('schematic')}<span>${type}_X1</span><small>${fmt(lib.delay*1000)} ps · demo</small></button>`).join('')}</div>`;return; }
  if(state.leftTab==='files'){ $('#tree').innerHTML=`<button class="tree-row" data-action="save">${icon('file')}<span class="tree-label">aurora_top.silicore</span></button><button class="tree-row" data-view="rtl">${icon('code')}<span class="tree-label">${esc(model.logic.name)}.v</span><span class="tree-number">RTL</span></button><button class="tree-row" data-action="settings">${icon('time')}<span class="tree-label">Clock constraints</span><span class="tree-number">${fmt(model.clock,2)} ns</span></button><button class="tree-row" data-action="timing">${icon('chart')}<span class="tree-label">Estimated timing report</span></button><button class="tree-row" data-action="exportDEF">${icon('download')}<span class="tree-label">Export placement.def</span></button>`;return; }
  if(filter){const found=model.cells.filter(c=>`${c.name} ${c.type} ${c.ref}`.toLowerCase().includes(filter));$('#tree').innerHTML=found.slice(0,150).map(c=>row(c.name,c.id,c.kind==='macro'?'box':'chip')).join('')||'<div class="tree-empty">No matching design objects</div>';return;}
  let html=row(model.name,'root','chip','',stats.cells+stats.macros,true);
  if(state.expanded.has('root')){
    html+=`<button class="tree-row indent" data-view="schematic">${icon('chevron','tree-arrow')}${icon('schematic','logic-icon')}<span class="tree-label">u_control</span><span class="tree-number">${model.logic.gates.length}</span></button>`;
    html+=row('Standard cells','cells','grid','indent',stats.cells,true);
    if(state.expanded.has('cells'))html+=model.cells.filter(c=>c.kind==='cell').slice(0,60).map(c=>row(c.name.split('/').at(-1),c.id,'chip','indent2')).join('');
    html+=row('Memory subsystem','memories','folder','indent',model.cells.filter(c=>c.kind==='macro'&&c.ref!=='PLL_DEMO').length,true);
    if(state.expanded.has('memories'))html+=model.cells.filter(c=>c.kind==='macro'&&c.ref!=='PLL_DEMO').map(c=>row(c.name,c.id,'box','indent2')).join('');
    html+=model.cells.filter(c=>c.kind==='macro'&&c.ref==='PLL_DEMO').map(c=>row(c.name,c.id,'time','indent')).join('');
  }
  $('#tree').innerHTML=html;
}
function renderFlow(){const entries=[['import','Read design','import'],['place','Place & legalize','place'],['route','Global routing','route'],['timing','Estimate timing','timing'],['check','Geometry checks','check']];$('#flowSteps').innerHTML=entries.map(([id,label,action],i)=>`<button class="flow-step ${state.flow[id]==='done'?'done':''} ${state.flow[id]==='busy'?'busy':''}" data-action="${action}"><span class="step-icon">${state.flow[id]==='done'?icon('check'):i+1}</span><span class="step-label">${label}</span><span class="step-status">${{done:'Complete',busy:'Running',preview:'Preview',estimated:'Estimated'}[state.flow[id]]||'Ready'}</span></button>`).join('');}
function prop(label,value,cls=''){return `<div class="property-row"><span>${label}</span><span class="${cls}">${value}</span></div>`;}
function renderInspector(){
  if(state.view==='schematic'&&state.schematicSelection){renderGateInspector();return;}
  const cells=selectedCells(),stats=designStats(model);$('#inspectorHeading').textContent=cells.length?'Properties':'Design overview';
  if(cells.length===1){const c=cells[0],nets=model.nets.filter(n=>n.from===c.id||n.to.includes(c.id));$('#inspector').innerHTML=`<div class="design-card"><div class="design-card-top"><span class="chip-tile">${icon(c.kind==='macro'?'box':'chip')}</span><div><h2>${esc(c.name.split('/').at(-1))}</h2><p>${esc(c.ref)} · ${c.kind==='macro'?'Physical macro':'Standard cell'}</p></div></div></div><section class="inspector-section"><h3>INSTANCE</h3><label class="property-row wide">Name<input data-prop="name" value="${esc(c.name)}" maxlength="256"></label>${prop('Reference',esc(c.ref))}${prop('Layer',c.layer==='macros'?'Macro blocks':'Standard cells')}<label class="property-row"><span>Fixed placement</span><input type="checkbox" data-prop="fixed" ${c.fixed?'checked':''}></label></section><section class="inspector-section"><h3>GEOMETRY <span class="muted">/ µm</span></h3>${['x','y','w','h'].map((k,i)=>`<label class="property-row"><span>${['Position X','Position Y','Width','Height'][i]}</span><input type="number" data-prop="${k}" value="${c[k]}" step="1" min="${i>1?1:-10000}" max="10000" ${i>1&&c.kind==='cell'?'readonly':''}></label>`).join('')}${prop('Area',`${fmt(c.w*c.h)} µm²`)}<button class="inspector-action" data-action="focusSelected">${icon('target')}Zoom to selection</button></section><section class="inspector-section"><h3>CONNECTIVITY</h3>${prop('Connected nets',nets.length)}${c.logicId?prop('RTL mapping',`control_unit / ${esc(c.logicId)}`):''}<div class="net-list">${nets.slice(0,20).map(n=>`<button data-net="${esc(n.id)}">${icon('route')} ${esc(n.name)}</button>`).join('')}</div></section><section class="inspector-section"><div class="inspector-note">${c.fixed?'Unlock fixed placement to move this macro.':'Drag the selected instance to edit placement. Hold Shift to extend the selection.'}</div><button class="inspector-action" data-action="duplicate">Duplicate instance</button><button class="inspector-action" data-action="delete">${icon('trash')}Delete instance</button></section>`;return;}
  if(cells.length>1){$('#inspector').innerHTML=`<div class="design-card"><div class="design-card-top"><span class="chip-tile">${icon('grid')}</span><div><h2>${cells.length} instances</h2><p>Multi-selection</p></div></div></div><section class="inspector-section"><h3>SELECTION</h3>${prop('Standard cells',cells.filter(c=>c.kind==='cell').length)}${prop('Macros',cells.filter(c=>c.kind==='macro').length)}${prop('Fixed instances',cells.filter(c=>c.fixed).length)}${prop('Total area',`${fmt(cells.reduce((a,c)=>a+c.w*c.h,0))} µm²`)}<button class="inspector-action" data-action="focusSelected">${icon('target')}Zoom to selection</button><button class="inspector-action" data-action="duplicate">Duplicate selection</button><button class="inspector-action" data-action="delete">${icon('trash')}Delete selection</button></section><section class="inspector-section"><div class="inspector-note">Drag to move all unlocked instances. Fixed instances remain in place.</div></section>`;return;}
  const t=state.timing;const macroArea=model.cells.filter(c=>c.kind==='macro').reduce((a,c)=>a+c.w*c.h,0),cellArea=stats.area-macroArea;
  const usage=clamp(stats.utilization*100,0,100);const macroPct=macroArea/stats.coreArea*100;
  const counts=Array.from({length:12},(_,i)=>model.cells.filter(c=>c.kind==='cell'&&Math.floor(c.x/model.die.w*12)===i).length);const max=Math.max(...counts,1);
  $('#inspector').innerHTML=`<div class="design-card"><div class="design-card-top"><span class="chip-tile">${icon('chip')}</span><div><h2>${esc(model.name)}</h2><p>Reference SoC floorplan</p></div></div><div class="design-card-bottom"><span class="small-dot"></span>Editable local design<span>DEMO-45</span></div></div><section class="inspector-section"><h3>DESIGN PROPERTIES</h3>${prop('Technology',esc(model.technology))}${prop('Die dimensions',`${fmt(model.die.w)} × ${fmt(model.die.h)}`)}${prop('Standard cells',fmt(stats.cells))}${prop('Macro blocks',fmt(stats.macros))}${prop('Signal nets',fmt(stats.nets))}${prop('Clock period',`${fmt(model.clock,2)} ns`)}</section><section class="inspector-section"><h3>CORE UTILIZATION</h3><div class="util-top"><div class="donut" style="background:conic-gradient(#83bd9b 0 ${Math.max(0,usage-macroPct)}%,#8279b5 ${Math.max(0,usage-macroPct)}% ${usage}%,#24333e ${usage}% 100%)"><strong>${fmt(usage)}<span style="font-size:8px">%</span></strong></div><div class="util-legend"><div class="legend-item"><i class="legend-swatch" style="background:#83bd9b"></i>Cells<b>${fmt(cellArea/stats.coreArea*100,1)}%</b></div><div class="legend-item"><i class="legend-swatch" style="background:#8279b5"></i>Macros<b>${fmt(macroPct,1)}%</b></div><div class="legend-item"><i class="legend-swatch" style="background:#344855"></i>Free<b>${fmt(100-usage,1)}%</b></div></div></div></section><section class="inspector-section"><h3>ESTIMATED TIMING ${state.timingStale?'<span class="tiny-tag">· STALE</span>':''}</h3><div class="timing-summary"><div class="timing-summary-label">Worst endpoint slack</div><div class="timing-number" style="${t.wns>=0?'color:#a1d0af':''}">${t.wns>=0?'+':''}${fmt(t.wns,3)} <small>ns</small></div><div class="timing-note">${icon(t.wns<0?'warning':'check')}${t.violations?`${t.violations} endpoints below target`:'All estimated endpoints meet target'}</div></div><button class="inspector-action" data-action="timing">${icon('time')}Analyze timing paths</button></section><section class="inspector-section"><h3>CELL DISTRIBUTION</h3><div class="mini-chart">${counts.map((n,i)=>`<i style="height:${8+n/max*37}px;background:${i>8?'#527b79':'#477d65'}" title="Bin ${i+1}: ${n} cells"></i>`).join('')}</div><div class="chart-axis"><span>0 µm</span><span>Die X position</span><span>${model.die.w}</span></div></section><section class="inspector-section"><div class="inspector-note">Synthetic library and geometric rules. Timing and routing are exploratory—not foundry-qualified signoff.</div></section>`;
}
function renderReports(){
  const t=state.timing;$('#timingCount').textContent=t.violations;$('#checkCount').textContent=state.checks.issues.length;
  $('#timingBody').innerHTML=`<div class="result-note">${state.timingStale?'STALE · rerun analysis after edits · ':''}Synthetic delay model · clock ${fmt(model.clock,3)} ns${t.cycles?` · ${t.cycles} cells in or downstream of cycles`:''} · click a path to cross-probe</div><table class="data-table"><thead><tr><th>STARTPOINT</th><th>ENDPOINT</th><th>DELAY (ns)</th><th>SLACK (ns)</th><th>STAGES</th></tr></thead><tbody>${t.paths.slice(0,35).map((p,i)=>`<tr data-path="${i}"><td>${esc(p.startpoint)}</td><td>${esc(p.endpoint)}</td><td>${fmt(p.delay,3)}</td><td class="${p.slack<0?'negative':'positive'}">${p.slack>0?'+':''}${fmt(p.slack,3)}</td><td>${p.ids.length}</td></tr>`).join('')}</tbody></table>`;
  $('#checksBody').innerHTML=state.checks.issues.length?`<div class="result-note">${state.checksStale?'STALE · ':''}Geometric rule deck only · ${state.checks.issues.length} issues${state.checks.truncated?' (truncated)':''} · click to locate</div><table class="data-table"><thead><tr><th>SEVERITY</th><th>RULE</th><th>DESCRIPTION</th></tr></thead><tbody>${state.checks.issues.map((p,i)=>`<tr data-issue="${i}"><td class="${p.severity==='error'?'negative':''}">${p.severity.toUpperCase()}</td><td>${p.rule}</td><td style="max-width:none">${esc(p.message)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty-state">${icon('checks')}<strong>${state.checksStale?'Design changed — checks need updating':'No geometric violations found'}</strong><span>Containment · placement overlap · net endpoints · route presence · demo wire width</span><span>Not a foundry DRC or LVS signoff result</span></div>`;
  const stats=designStats(model);$('#summaryBody').innerHTML=`<div class="result-metrics"><div class="result-metric"><small>PLACED INSTANCES</small><strong>${fmt(model.cells.length)}</strong></div><div class="result-metric"><small>CORE UTILIZATION</small><strong>${fmt(stats.utilization*100,1)} <span>%</span></strong></div><div class="result-metric"><small>ROUTED WIRE LENGTH</small><strong>${fmt(stats.wireLength/1000,1)} <span>mm</span></strong></div><div class="result-metric"><small>RTL LOGIC NODES</small><strong>${model.logic.gates.length}</strong></div></div><div class="result-meta">${esc(model.name)} · ${fmt(model.die.w)} × ${fmt(model.die.h)} µm · ${fmt(stats.nets)} nets · ${esc(renderer.backend)} · Local revision ${state.revision}</div>`;
}

function drawMinimap(){const canvas=$('#minimap'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#09121a';ctx.fillRect(0,0,W,H);const scale=Math.min((W-18)/model.die.w,(H-16)/model.die.h),ox=(W-model.die.w*scale)/2,oy=(H-model.die.h*scale)/2;ctx.strokeStyle='#486575';ctx.lineWidth=.7;ctx.strokeRect(ox,oy,model.die.w*scale,model.die.h*scale);for(const c of model.cells){ctx.fillStyle=c.kind==='macro'?(c.color||'#8175b0'):'#39765e';ctx.globalAlpha=c.kind==='macro'?.7:.5;ctx.fillRect(ox+c.x*scale,oy+c.y*scale,Math.max(.5,c.w*scale),Math.max(.5,c.h*scale));}ctx.globalAlpha=1;const c=renderer.camera;ctx.strokeStyle='#b2ddc5';ctx.fillStyle='#a7efc614';ctx.lineWidth=1;const x=ox+c.x*scale,y=oy+c.y*scale,w=c.width/c.zoom*scale,h=c.height/c.zoom*scale;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);}
function drawOverlay(ctx,camera){
  const to=(x,y)=>camera.worldToScreen(x,y);const chosen=state.selection;
  const highlightNets=new Set();for(const n of model.nets)if(n.id===state.selectedNet||chosen.has(n.from)||n.to.some(id=>chosen.has(id)))highlightNets.add(n.id);
  if(state.mode==='timing'&&state.timing.paths[0]){const ids=new Set(state.timing.paths[0].ids);for(const n of model.nets)if(ids.has(n.from)&&n.to.some(id=>ids.has(id)))highlightNets.add(n.id);}
  if(highlightNets.size){ctx.strokeStyle=state.mode==='timing'?'#f0b279':'#b8f6d0';ctx.lineWidth=1.3;ctx.globalAlpha=.87;ctx.beginPath();for(const n of model.nets)if(highlightNets.has(n.id))for(const l of n.segments||[]){const a=to(l.x1,l.y1),b=to(l.x2,l.y2);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);}ctx.stroke();ctx.globalAlpha=1;}
  for(const cell of model.cells){if(!chosen.has(cell.id)&&cell.id!==state.hover)continue;const p=to(cell.x,cell.y),w=cell.w*camera.zoom,h=cell.h*camera.zoom;ctx.strokeStyle=chosen.has(cell.id)?'#c3f8d8':'#a3bbc5';ctx.lineWidth=chosen.has(cell.id)?1.5:1;ctx.fillStyle='#b1f5ce1a';ctx.fillRect(p.x-1,p.y-1,w+2,h+2);ctx.strokeRect(p.x-1,p.y-1,w+2,h+2);if(chosen.has(cell.id)&&cell.kind==='macro'){ctx.fillStyle='#bcebd0';for(const [x,y]of[[p.x,p.y],[p.x+w,p.y],[p.x,p.y+h],[p.x+w,p.y+h]])ctx.fillRect(x-2,y-2,4,4);}}
  const drag=state.pointer;if(drag&&(drag.kind==='box'||drag.kind==='macro')){const a=to(drag.start.x,drag.start.y),b=to(drag.last.x,drag.last.y);ctx.strokeStyle=drag.kind==='macro'?'#bfa4e8':'#a3d8be';ctx.fillStyle=drag.kind==='macro'?'#b996e320':'#95debf12';ctx.setLineDash([4,3]);ctx.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);ctx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y);ctx.setLineDash([]);}
  const measure=drag?.kind==='measure'?{a:drag.start,b:drag.last}:state.measure;if(measure){const a=to(measure.a.x,measure.a.y),b=to(measure.b.x,measure.b.y);ctx.strokeStyle='#dec28c';ctx.lineWidth=1;ctx.setLineDash([5,3]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);for(const p of[a,b]){ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.stroke();}const distance=Math.hypot(measure.b.x-measure.a.x,measure.b.y-measure.a.y);ctx.font='10px SFMono-Regular,Consolas,monospace';const text=`${distance.toFixed(2)} µm`,tw=ctx.measureText(text).width;const x=(a.x+b.x)/2-tw/2,y=(a.y+b.y)/2-12;ctx.fillStyle='#192827';ctx.fillRect(x-6,y-10,tw+12,19);ctx.fillStyle='#e2c894';ctx.textAlign='left';ctx.fillText(text,x,y);}
  if(state.routeStart&&state.mouse){const cell=model.cells.find(c=>c.id===state.routeStart);if(cell){const p=to(cell.x+cell.w,cell.y+cell.h/2),q=to(state.mouse.x,state.mouse.y);ctx.strokeStyle='#b3dfbc';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.setLineDash([]);}}
  if(state.hover&&!drag){const cell=model.cells.find(c=>c.id===state.hover);if(cell){ctx.font='10px SFMono-Regular,Consolas,monospace';ctx.textAlign='left';ctx.fillStyle='#839fac';ctx.fillText(cell.name,15,camera.height-46);}}
  updateCameraStatus();
}

function pointerPosition(e){const r=$('#interaction').getBoundingClientRect();const screen={x:e.clientX-r.left,y:e.clientY-r.top};return {screen,world:renderer.camera.screenToWorld(screen.x,screen.y)};}
const snapPoint=p=>state.snap?{x:Math.round(p.x),y:Math.round(p.y)}:p;
function queueGeometry(){if(uiFrame)return;uiFrame=requestAnimationFrame(()=>{uiFrame=0;refreshScene();});}
const surface=$('#interaction');
surface.addEventListener('contextmenu',e=>e.preventDefault());
surface.addEventListener('pointerdown',e=>{
  if(state.busy)return;surface.focus();surface.setPointerCapture(e.pointerId);const {screen,world}=pointerPosition(e),p=snapPoint(world);
  if(e.button===1||e.button===2||state.space||state.tool==='hand'){state.pointer={kind:'pan',screen,camera:{x:renderer.camera.x,y:renderer.camera.y}};surface.style.cursor='grabbing';return;}
  if(e.button!==0)return;
  const hit=spatial.point(world.x,world.y,2/renderer.camera.zoom).find(c=>state.layers.find(l=>l.id===c.layer)?.visible!==false);
  if(state.tool==='route'){if(!hit){toast('Select a placed cell or macro endpoint.');return;}if(!state.routeStart){state.routeStart=hit.id;selectCells([hit.id]);setHint(`Source: ${hit.name} · select a destination`);}else{const start=state.routeStart;if(start===hit.id){toast('Choose a different destination.');return;}transact('Connect instances',()=>{model.nets.push({id:`user-net:${newID()}`,name:`user_net_${model.nets.length+1}`,from:start,to:[hit.id],width:.7,layer:'M1',segments:[]});model.nets=quickRoute(model);});state.routeStart=null;selectCells([start,hit.id]);setHint('Connection created · select another source cell');}return;}
  if(state.tool==='macro'){state.pointer={kind:'macro',start:p,last:p,screen};return;}
  if(state.tool==='measure'){state.pointer={kind:'measure',start:p,last:p,screen};return;}
  const selected=selectedCells();if(selected.length===1&&!selected[0].fixed&&selected[0].kind==='macro'){const c=selected[0];const corners=[[c.x,c.y,c.x+c.w,c.y+c.h],[c.x+c.w,c.y,c.x,c.y+c.h],[c.x,c.y+c.h,c.x+c.w,c.y],[c.x+c.w,c.y+c.h,c.x,c.y]];for(const [x,y,ax,ay]of corners){const q=renderer.camera.worldToScreen(x,y);if(Math.hypot(screen.x-q.x,screen.y-q.y)<7){history.begin(model,'Resize macro');state.pointer={kind:'resize',id:c.id,start:p,last:p,anchor:{x:ax,y:ay},screen,moved:false};return;}}}
  if(hit){if(e.shiftKey){if(state.selection.has(hit.id))state.selection.delete(hit.id);else state.selection.add(hit.id);renderInspector();renderTree();}else if(!state.selection.has(hit.id))selectCells([hit.id]);const movable=selectedCells().filter(c=>!c.fixed);if(movable.length){history.begin(model,'Move instances');state.pointer={kind:'move',start:p,last:p,screen,moved:false,original:movable.map(c=>({id:c.id,x:c.x,y:c.y}))};}else{status(`${hit.name} is fixed. Unlock it in Properties to move.`);renderer.invalidate();}}
  else {if(!e.shiftKey)selectCells([]);state.pointer={kind:'box',start:p,last:p,screen,extend:e.shiftKey};}
});
surface.addEventListener('pointermove',e=>{
  const {screen,world}=pointerPosition(e),p=snapPoint(world);state.mouse=world;$('#coordinates').textContent=`X ${fmt(world.x,2)} · Y ${fmt(world.y,2)} µm`;const drag=state.pointer;
  if(drag){if(drag.kind==='pan'){renderer.camera.x=drag.camera.x-(screen.x-drag.screen.x)/renderer.camera.zoom;renderer.camera.y=drag.camera.y-(screen.y-drag.screen.y)/renderer.camera.zoom;drawMinimap();renderer.invalidate();return;}drag.last=p;drag.moved=drag.moved||Math.hypot(screen.x-drag.screen.x,screen.y-drag.screen.y)>3;
    if(drag.kind==='move'&&drag.moved){const dx=p.x-drag.start.x,dy=p.y-drag.start.y;for(const o of drag.original){const cell=spatial.items.get(o.id);cell.x=o.x+dx;cell.y=o.y+dy;}model.nets=quickRoute(model);queueGeometry();}
    else if(drag.kind==='resize'&&drag.moved){const cell=spatial.items.get(drag.id);cell.x=Math.min(p.x,drag.anchor.x);cell.y=Math.min(p.y,drag.anchor.y);cell.w=Math.max(4,Math.abs(p.x-drag.anchor.x));cell.h=Math.max(4,Math.abs(p.y-drag.anchor.y));model.nets=quickRoute(model);queueGeometry();}
    else renderer.invalidate();return;
  }
  const hit=spatial.point(world.x,world.y,1/renderer.camera.zoom).find(c=>state.layers.find(l=>l.id===c.layer)?.visible!==false);if(state.hover!==(hit?.id||null)||state.routeStart){state.hover=hit?.id||null;renderer.invalidate();}
});
function endPointer(e){const drag=state.pointer;if(!drag)return;state.pointer=null;if(e&&surface.hasPointerCapture(e.pointerId))surface.releasePointerCapture(e.pointerId);
  if(['move','resize'].includes(drag.kind)){if(history.commit(model)){markChanged();$('#layoutCaption').textContent='Edited placement · preview routes';status(drag.kind==='resize'?'Macro resized':'Placement updated');}}
  else if(drag.kind==='box'){const x=Math.min(drag.start.x,drag.last.x),y=Math.min(drag.start.y,drag.last.y),w=Math.abs(drag.start.x-drag.last.x),h=Math.abs(drag.start.y-drag.last.y);if(w+h>4)selectCells(spatial.query({x,y,w,h}).filter(c=>state.layers.find(l=>l.id===c.layer)?.visible!==false).map(c=>c.id),{extend:drag.extend});}
  else if(drag.kind==='macro'){const w=Math.abs(drag.start.x-drag.last.x),h=Math.abs(drag.start.y-drag.last.y);if(w<8||h<8){toast('Drag a larger rectangle to create a macro.');}else{const id=`macro:${newID()}`;transact('Create macro',()=>model.cells.push({id,name:`U_MACRO_${model.cells.filter(c=>c.kind==='macro').length+1}`,kind:'macro',type:'MACRO',ref:'USER_MACRO',x:Math.min(drag.start.x,drag.last.x),y:Math.min(drag.start.y,drag.last.y),w,h,layer:'macros',fixed:false,color:'#8e7fbc',label:'User macro',detail:'Editable physical block'}));selectCells([id]);}}
  else if(drag.kind==='measure'){state.measure={a:drag.start,b:drag.last};status(`Distance: ${fmt(Math.hypot(drag.last.x-drag.start.x,drag.last.y-drag.start.y),2)} µm`);}
  surface.style.cursor=state.tool==='hand'?'grab':state.tool==='select'?'default':'crosshair';renderer.invalidate();
}
surface.addEventListener('pointerup',endPointer);
surface.addEventListener('pointercancel',()=>{if(history.pending){model=history.cancel()||model;spatial.rebuild(model.cells);refreshScene();}state.pointer=null;renderer.invalidate();});
surface.addEventListener('wheel',e=>{e.preventDefault();const {screen}=pointerPosition(e);renderer.camera.zoomAt(screen.x,screen.y,Math.exp(-e.deltaY*.0015));renderer.invalidate();drawMinimap();updateCameraStatus();},{passive:false});
surface.addEventListener('dblclick',e=>{const {world}=pointerPosition(e);const hit=spatial.point(world.x,world.y,2/renderer.camera.zoom)[0];if(hit?.logicId){state.schematicSelection=hit.logicId;setView('schematic');}else if(hit)selectCells([hit.id],{focus:true});else fit();});
$('#minimap').addEventListener('pointerdown',e=>{const canvas=e.currentTarget,r=canvas.getBoundingClientRect();const x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,scale=Math.min((canvas.width-18)/model.die.w,(canvas.height-16)/model.die.h),ox=(canvas.width-model.die.w*scale)/2,oy=(canvas.height-model.die.h*scale)/2;renderer.camera.x=(x-ox)/scale-renderer.camera.width/renderer.camera.zoom/2;renderer.camera.y=(y-oy)/scale-renderer.camera.height/renderer.camera.zoom/2;renderer.invalidate();drawMinimap();});
$('#bottomResizer').addEventListener('pointerdown',e=>{e.currentTarget.setPointerCapture(e.pointerId);state.bottomDrag={y:e.clientY,height:$('#bottomPanel').getBoundingClientRect().height};});
$('#bottomResizer').addEventListener('pointermove',e=>{if(state.bottomDrag){const max=Math.max(80,$('.center-panel').clientHeight-300);document.documentElement.style.setProperty('--bottom',`${clamp(state.bottomDrag.height+state.bottomDrag.y-e.clientY,80,max)}px`);}});
$('#bottomResizer').addEventListener('pointerup',()=>{state.bottomDrag=null;});

function setBusy(busy,label='Run implementation'){state.busy=busy;$('#runFlow').disabled=busy;$('#runFlow').classList.toggle('running',busy);$('#runFlow span').textContent=busy?label:'Run implementation';$$('[data-action="synthesize"],[data-action="simulate"]').forEach(b=>b.disabled=busy);}
async function executeTask(type){
  const payload=type==='compile'?$('#hdlEditor').value:type==='simulate'?{logic:model.logic,cycles:Number($('#sampleCount').value),overrides:{}}:model;
  const before=state.revision;const result=await engine.run(type,payload,p=>status(`Routing ${Math.round(p*100)}% · UI remains interactive`));if(before!==state.revision)throw new Error('Design changed during analysis; stale result discarded.');
  if(type==='compile'){
    const synthesized=synthesizeInto(model,result.result);history.begin(model,'Synthesize RTL');model=synthesized;history.commit(model);state.flow.import='done';state.flow.place='done';state.flow.route='preview';state.inputs={};state.schematicSelection=null;syncEditor(model.hdl);$('#editorDiagnostic').hidden=true;state.simulation=simulate(model.logic);markChanged();renderSchematic();log('success',`Elaborated ${model.logic.name}: ${model.logic.gates.length} logic nodes, ${model.logic.inputs.length} inputs, ${model.logic.outputs.length} outputs (${fmt(result.elapsed,1)} ms).`);toast(`Synthesized ${model.logic.name} · ${model.logic.gates.length} logic nodes`);$('#layoutCaption').textContent='RTL updated · placement legalized';
  }else if(type==='place'){
    history.begin(model,'Legalize placement');model.cells=result.result.cells;model.nets=quickRoute(model);history.commit(model);state.flow.place='done';state.flow.route='preview';markChanged();log(result.result.failed?'warn':'success',`Placed ${fmt(result.result.placed)} instances; ${result.result.failed} did not fit (${fmt(result.elapsed,1)} ms).`);$('#layoutCaption').textContent='Legalized placement · preview routes';
  }else if(type==='route'){
    history.begin(model,'Global route');model.nets=result.result.nets;history.commit(model);state.flow.route=result.result.failed?'partial':'done';markChanged();log(result.result.failed?'warn':'success',`A* routing: ${fmt(result.result.routed)} connections routed, ${result.result.failed} failed (${fmt(result.elapsed,1)} ms).`);log('info','Macro-obstacle routing on a 16 µm grid. Spacing, via and electrical signoff are not modeled.');$('#layoutCaption').textContent=`A* routed · ${result.result.failed} unrouted connections`;
  }else if(type==='timing'){
    state.timing=result.result;state.timingStale=false;state.flow.timing='done';renderInspector();renderReports();renderer.invalidate();log('info',`Estimated WNS ${fmt(state.timing.wns,3)} ns; TNS ${fmt(state.timing.tns,3)} ns; ${state.timing.violations} violating endpoints (${fmt(result.elapsed,1)} ms).`);if(state.timing.cycles)log('warn',`${state.timing.cycles} cells are in or downstream of cycles; their timing is not valid.`);
  }else if(type==='check'){
    state.checks=result.result;state.checksStale=false;state.flow.check='done';renderReports();log(state.checks.issues.length?'warn':'success',`${state.checks.issues.length} geometric issues found (${fmt(result.elapsed,1)} ms). Not foundry signoff.`);
  }else if(type==='simulate'){
    state.simulation=result.result;state.cursor=0;setView('wave');renderWave();log('success',`Simulated ${result.result.cycles} combinational samples across ${result.result.signals.length} signals (${fmt(result.elapsed,1)} ms).`);
  }
  renderFlow();return result.result;
}
async function runTask(type){if(state.busy){toast('An implementation task is already running.');return;}setBusy(true,{place:'Placing…',route:'Routing…',timing:'Analyzing…',check:'Checking…',compile:'Synthesizing…',simulate:'Simulating…'}[type]);const flowKey=type==='compile'?'import':type;const old=state.flow[flowKey];if(flowKey in state.flow)state.flow[flowKey]='busy';renderFlow();status(`${type} running in worker`);
  try{await executeTask(type);status(`${type} complete`);if(type==='timing')setBottom('timing');if(type==='check')setBottom('checks');}catch(e){state.flow[flowKey]=old;if(type==='compile')showHDLError(e);handleError(e);}finally{setBusy(false);renderFlow();}
}
async function runFlow(){if(state.busy)return;setBusy(true,'Implementing…');setBottom('console');log('info','Implementation started: row legalization → A* global routing → timing estimate → geometric checks.');try{for(const type of ['place','route','timing','check']){state.flow[type]='busy';renderFlow();status(`${type} running in worker`);await executeTask(type);}status('Implementation complete');toast(`Implementation complete · ${state.checks.issues.length} geometric issues`);}catch(e){handleError(e);}finally{for(const k of Object.keys(state.flow))if(state.flow[k]==='busy')state.flow[k]='ready';setBusy(false);renderFlow();}}
function undo(redo=false){if(state.busy)return;const entry=redo?history.redo(model):history.undo(model);if(!entry){status(redo?'Nothing to redo':'Nothing to undo');return;}model=entry.model;state.selection.clear();state.schematicSelection=null;state.inputs={};state.simulation=simulate(model.logic);markChanged();syncEditor(model.hdl);if(state.view==='schematic')renderSchematic();if(state.view==='wave')renderWave();toast(`${redo?'Redid':'Undid'} ${entry.label.toLowerCase()}`);}
function deleteSelected(){if(state.view==='schematic'&&state.schematicSelection){const id=state.schematicSelection;editLogic('Delete logic node',logic=>{const gate=logic.gates.find(g=>g.id===id);if(!gate)return;const replacement=gate.inputs[0]||'const:1:0';logic.gates=logic.gates.filter(g=>g.id!==id);for(const g of logic.gates)g.inputs=g.inputs.map(x=>x===id?replacement:x);for(const p of logic.outputs)if(p.source===id)p.source=replacement;});state.schematicSelection=null;return;}
  const cells=selectedCells();if(!cells.length)return;const unlocked=cells.filter(c=>!c.fixed);if(!unlocked.length){toast('Unlock fixed instances in Properties before deleting.');return;}const ids=new Set(unlocked.map(c=>c.id));transact('Delete instances',()=>{model.cells=model.cells.filter(c=>!ids.has(c.id));model.nets=model.nets.filter(n=>!ids.has(n.from)).map(n=>({...n,to:n.to.filter(id=>!ids.has(id))})).filter(n=>n.to.length);});state.selection.clear();renderInspector();renderer.invalidate();}
function duplicate(){const cells=selectedCells();if(!cells.length)return;const newIds=[];transact('Duplicate instances',()=>{for(const c of cells){const item=clone(c);item.id=`copy:${newID()}`;item.name=`${c.name}_copy`;item.x+=25;item.y+=25;item.fixed=false;delete item.logicId;newIds.push(item.id);model.cells.push(item);}});selectCells(newIds);}
function insertCell(type){if(state.view==='schematic'){addLogicGate(type);return;}setView('layout');const p=renderer.camera.screenToWorld(renderer.camera.width/2,renderer.camera.height/2);const id=`cell:${newID()}`;transact(`Insert ${type} cell`,()=>model.cells.push({id,name:`u_user/${type.toLowerCase()}_${model.cells.length+1}`,kind:'cell',type,ref:`${type}_X1`,x:Math.round(p.x),y:Math.round(p.y),w:LIBRARY[type].area,h:10,layer:'cells',fixed:false}));selectCells([id]);setTool('select');toast(`${type}_X1 inserted at the viewport center. Drag to place it.`);}
function syncEditor(source){$('#hdlEditor').value=source;highlightCode();updateEditorPosition();$('#rtlFilename').textContent=`${model.logic.name}.v`;}
function highlightCode(){const source=$('#hdlEditor').value;const regex=/\/\/[^\n]*|\/\*[\s\S]*?\*\/|\b(?:module|endmodule|input|output|wire|logic|assign)\b|\b\d+(?:'[bhd][\da-fA-F_]+)?\b|[~!&|^?:+=-]/g;let html='',last=0,m;while((m=regex.exec(source))){html+=esc(source.slice(last,m.index));const v=m[0];const cls=v.startsWith('//')||v.startsWith('/*')?'comment':/^(module|endmodule|input|output|wire|logic|assign)$/.test(v)?'keyword':/^\d/.test(v)?'number':'op';html+=`<span class="tok-${cls}">${esc(v)}</span>`;last=m.index+v.length;}html+=esc(source.slice(last));$('#codeHighlight').innerHTML=html+'\n';$('#lineNumbers').textContent=source.split('\n').map((_,i)=>i+1).join('\n');syncEditorScroll();}
function syncEditorScroll(){$('#codeHighlight').scrollTop=$('#hdlEditor').scrollTop;$('#codeHighlight').scrollLeft=$('#hdlEditor').scrollLeft;$('#lineNumbers').scrollTop=$('#hdlEditor').scrollTop;}
function updateEditorPosition(){const el=$('#hdlEditor'),text=el.value.slice(0,el.selectionStart),lines=text.split('\n');$('#editorPosition').textContent=`Ln ${lines.length}, Col ${lines.at(-1).length+1}`;}
function showHDLError(error){setView('rtl');$('#editorDiagnostic').hidden=false;$('#editorDiagnostic').textContent=error.message;if(error.line){const lines=$('#hdlEditor').value.split('\n');const start=lines.slice(0,error.line-1).reduce((a,l)=>a+l.length+1,0);$('#hdlEditor').setSelectionRange(start,start+(lines[error.line-1]?.length||0));$('#hdlEditor').scrollTop=Math.max(0,(error.line-3)*23);syncEditorScroll();}}
$('#hdlEditor').addEventListener('input',()=>{highlightCode();updateEditorPosition();queueSave();$('#rtlFilename').textContent=`${model.logic.name}.v${$('#hdlEditor').value!==model.hdl?' •':''}`;});
$('#hdlEditor').addEventListener('scroll',syncEditorScroll);$('#hdlEditor').addEventListener('click',updateEditorPosition);$('#hdlEditor').addEventListener('keyup',updateEditorPosition);
$('#hdlEditor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const el=e.currentTarget;el.setRangeText('    ',el.selectionStart,el.selectionEnd,'end');el.dispatchEvent(new Event('input'));}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void runTask('compile');}});

function schematicPoint(e){const svg=$('#schematicSvg'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const matrix=svg.getScreenCTM();return matrix?p.matrixTransform(matrix.inverse()):{x:0,y:0};}
function renderSchematic(forceFit=false){
  const logic=model.logic;$('#schematicModule').textContent=logic.name;let values;try{values=evaluateLogic(logic,state.inputs);}catch(e){handleError(e);return;}
  const ordered=orderedGates(logic),levels=new Map(logic.inputs.map(p=>[`in:${p.name}`,0])),groups=new Map();for(const g of ordered){const level=Math.max(0,...g.inputs.map(i=>levels.get(i)||0))+1;levels.set(g.id,level);if(!groups.has(level))groups.set(level,[]);groups.get(level).push(g);}
  const maxLevel=Math.max(1,...levels.values()),maxGroup=Math.max(1,...[...groups.values()].map(a=>a.length));const height=Math.max(490,maxGroup*98+100,Math.max(logic.inputs.length,logic.outputs.length)*77+100),width=250+maxLevel*156+160;
  const positions=new Map(),sources=new Map(),targets=new Map();
  for(const [i,p]of logic.inputs.entries()){const y=72+i*(height-140)/Math.max(1,logic.inputs.length-1);sources.set(`in:${p.name}`,{x:133,y});}
  for(const [level,list]of groups)for(let i=0;i<list.length;i++){const g=list[i];const saved=logic.positions?.[g.id],p=saved||{x:180+(level-1)*156,y:height/2+(i-(list.length-1)/2)*104-27};positions.set(g.id,p);sources.set(g.id,{x:p.x+94,y:p.y+27});targets.set(g.id,g.inputs.map((_,index)=>({x:p.x-12,y:p.y+(index+1)*54/(g.inputs.length+1)})));}
  const getValue=id=>id.startsWith('const:')?Number(id.split(':')[2]):values.values[id];
  let svg=`<defs><filter id="gate-shadow" x="-20%" y="-40%" width="140%" height="180%"><feDropShadow dx="0" dy="3" stdDeviation="4" flood-opacity=".2"/></filter></defs>`;
  for(const [level]of groups)svg+=`<text x="${180+(level-1)*156+34}" y="27" fill="#3f6073" font-size="8" font-family="monospace" text-anchor="middle">LEVEL ${level}</text>`;
  svg+=`<text x="68" y="27" fill="#527969" font-size="8" font-family="monospace" text-anchor="middle">PRIMARY INPUTS</text><text x="${width-63}" y="27" fill="#527969" font-size="8" font-family="monospace" text-anchor="middle">OUTPUTS</text>`;
  for(const g of logic.gates)for(const [i,id]of g.inputs.entries()){const to=targets.get(g.id)?.[i];let from=sources.get(id);if(!to)continue;if(!from&&id.startsWith('const:')){from={x:to.x-28,y:to.y};svg+=`<text x="${from.x-5}" y="${from.y+3}" font-size="9" fill="#b9bc8f" text-anchor="end">${esc(id.split(':')[2])}</text>`;}if(!from)continue;const mid=from.x+Math.max(12,(to.x-from.x)*.46);svg+=`<path class="schematic-wire ${getValue(id)?'high':''}" d="M${from.x},${from.y} H${mid} V${to.y} H${to.x}"/>`;}
  for(const [i,p]of logic.outputs.entries()){const to={x:width-123,y:72+i*(height-140)/Math.max(1,logic.outputs.length-1)},from=sources.get(p.source);if(from)svg+=`<path class="schematic-wire ${values.outputs[p.name]?'high':''}" d="M${from.x},${from.y} H${to.x-25} V${to.y} H${to.x}"/>`;const value=values.outputs[p.name];svg+=`<g transform="translate(${to.x},${to.y-18})"><path d="M0 18 L10 0 H108 V36 H10 Z" fill="#183127" stroke="#48755b"/><text x="18" y="15" fill="#b0d2c0" font-size="10" font-family="monospace">${esc(p.name)}</text><text x="18" y="28" fill="#638c79" font-size="8">${p.width>1?`${p.width}-bit bus`:'output'}</text><text x="97" y="22" fill="${value?'#b7f6c6':'#698b7d'}" font-size="11" font-family="monospace" text-anchor="end">${value===null?'X':p.width>1?value.toString(16):value}</text><circle class="port-hit" cx="0" cy="18" r="5" data-output-name="${esc(p.name)}"/></g>`;}
  for(const [i,p]of logic.inputs.entries()){const pos=sources.get(`in:${p.name}`),value=state.inputs[p.name]??0;svg+=`<g class="input-node" data-input-toggle="${esc(p.name)}" transform="translate(14,${pos.y-18})"><path d="M0 0 H106 L119 18 L106 36 H0 Z" fill="${value?'#254c37':'#172a28'}" stroke="${value?'#8acbab':'#486958'}"/><text x="10" y="15" fill="#b1cebd" font-size="10" font-family="monospace">${esc(p.name)}</text><text x="10" y="28" fill="#5f8978" font-size="8">${p.width>1?`${p.width}-bit · click to increment`:'click to toggle'}</text><text x="98" y="23" fill="${value?'#c3ffd7':'#809c8c'}" font-family="monospace" font-size="13" text-anchor="end">${p.width>1?value.toString(16):value}</text><circle class="port-hit" cx="119" cy="18" r="4" data-source="in:${esc(p.name)}"/></g>`;}
  for(const g of logic.gates){const p=positions.get(g.id),color=LIBRARY[g.type]?.color||'#548776';let shape;
    if(['AND','NAND','LAND'].includes(g.type))shape='<path class="gate-body" d="M0 0 H40 C93 0 93 54 40 54 H0 Z"/>';
    else if(['OR','NOR','XOR','LOR'].includes(g.type))shape=`<path class="gate-body" d="M0 0 Q23 27 0 54 Q53 55 82 27 Q53 -1 0 0 Z"/>${g.type==='XOR'?'<path d="M-7 0 Q16 27 -7 54" fill="none"/>':''}`;
    else if(['NOT','BUF','LNOT'].includes(g.type))shape='<path class="gate-body" d="M2 0 L78 27 L2 54 Z"/>';
    else if(g.type==='MUX')shape='<path class="gate-body" d="M0 0 L79 8 V46 L0 54 Z"/>';
    else shape='<rect class="gate-body" x="0" y="0" width="79" height="54" rx="5"/>';
    const invert=['NOT','NAND','NOR','LNOT'].includes(g.type);const value=getValue(g.id);svg+=`<g class="schematic-node ${state.schematicSelection===g.id?'selected':''}" data-gate="${esc(g.id)}" transform="translate(${p.x},${p.y})"><text x="37" y="-11" fill="#698da1" font-size="8" font-family="monospace" text-anchor="middle">${esc(g.name)}</text><g fill="#14242f" stroke="${color}" stroke-width="1.4" filter="url(#gate-shadow)">${shape}</g>${invert?`<circle cx="82" cy="27" r="4" fill="#14242f" stroke="${color}" stroke-width="1.4"/>`:''}<path d="M${invert?86:79} 27 H94" stroke="${color}" stroke-width="1.4"/><text x="${['NOT','BUF'].includes(g.type)?27:37}" y="31" fill="#afc0c8" font-size="${g.type.length>4?8:10}" font-family="monospace" text-anchor="middle">${g.type==='ADD'?'+':g.type==='SUB'?'−':g.type==='EQ'?'=':g.type}</text>${g.inputs.map((id,i)=>{const y=(i+1)*54/(g.inputs.length+1);return `<path d="M-12 ${y} H${['OR','NOR','XOR','LOR'].includes(g.type)?8:2}" stroke="${color}" stroke-width="1.4"/><circle class="port-hit" cx="-12" cy="${y}" r="4.5" data-target="${esc(g.id)}" data-pin="${i}"/>`;}).join('')}<circle class="port-hit" cx="94" cy="27" r="4.5" data-source="${esc(g.id)}"/><text x="38" y="69" fill="${value?'#84cba1':'#3f6476'}" font-size="8" font-family="monospace" text-anchor="middle">${g.width>1?`${g.width}-bit · `:''}${value===null?'X':g.width>1?'0x'+value.toString(16):value}</text></g>`;
  }
  const el=$('#schematicSvg');el.innerHTML=svg;if(forceFit||!schematicGeometry||schematicGeometry.logic!==logic)el.setAttribute('viewBox',`-10 -4 ${width+20} ${height+10}`);schematicGeometry={logic,width,height,positions,sources,targets};
  renderGateInspectorIfSelected();
}
function renderGateInspectorIfSelected(){if(state.view==='schematic'&&state.schematicSelection)renderGateInspector();}
function renderGateInspector(){const g=model.logic.gates.find(g=>g.id===state.schematicSelection);if(!g){state.schematicSelection=null;renderInspector();return;}$('#inspectorHeading').textContent='Logic properties';const current=evaluateLogic(model.logic,state.inputs).values[g.id];$('#inspector').innerHTML=`<div class="design-card"><div class="design-card-top"><span class="chip-tile">${icon('schematic')}</span><div><h2>${esc(g.name)}</h2><p>${g.type} · ${g.width}-bit</p></div></div></div><section class="inspector-section"><h3>LOGIC NODE</h3>${prop('Instance ID',esc(g.id))}<label class="property-row"><span>Gate type</span><select id="gateType">${Object.entries(LIBRARY).filter(([t,l])=>l.arity===g.inputs.length&&(t!=='SLICE'||g.type==='SLICE')).map(([t])=>`<option ${t===g.type?'selected':''}>${t}</option>`).join('')}</select></label>${prop('Signal width',`${g.width} bit${g.width===1?'':'s'}`)}${prop('Current output',current===null?'X':fmt(current))}${prop('Demo delay',`${fmt((LIBRARY[g.type]?.delay||0)*1000)} ps`)}</section><section class="inspector-section"><h3>CONNECTIONS</h3>${g.inputs.map((id,i)=>prop(`Input ${i}`,esc(id))).join('')}<div class="inspector-note" style="margin-top:10px">Connect an output pin to an input pin to rewire. Cyclic connections are rejected. Changes update the HDL and mapped control cells.</div><button class="inspector-action" data-action="crossProbe">${icon('chip')}Locate in physical design</button><button class="inspector-action" data-action="delete">${icon('trash')}Delete logic node</button></section>`;
}
function editLogic(label,edit){if(state.busy)return;let successful=false;transact(label,()=>{const logic=clone(model.logic);edit(logic);validateLogic(logic);logic.source=logicToHDL(logic);model=synthesizeInto(model,logic);state.simulation=simulate(logic,Number($('#sampleCount').value));successful=true;});if(successful){syncEditor(model.hdl);renderSchematic();if(state.view==='wave')renderWave();toast(label);}}
function addLogicGate(type='AND'){const id=`g_user_${Date.now().toString(36)}`;editLogic(`Add ${type} logic node`,logic=>{const inputRefs=logic.inputs.map(p=>`in:${p.name}`);logic.gates.push({id,name:`u_${type.toLowerCase()}_${logic.gates.length+1}`,type,width:1,inputs:Array.from({length:LIBRARY[type].arity},(_,i)=>inputRefs[i%Math.max(1,inputRefs.length)]||'const:1:0')});});state.schematicSelection=id;renderSchematic();}
$('#schematicSvg').addEventListener('click',e=>{
  if(state.preventSchematicClick){state.preventSchematicClick=false;return;}const source=e.target.closest('[data-source]'),target=e.target.closest('[data-target]'),output=e.target.closest('[data-output-name]');
  if(source){state.wireStart=source.dataset.source;$('.schematic-hint').textContent=`Connecting ${state.wireStart} · click a destination input pin or module output · Escape cancels`;return;}
  if(state.wireStart&&(target||output)){const from=state.wireStart;state.wireStart=null;editLogic('Update logic connection',logic=>{if(target){const g=logic.gates.find(g=>g.id===target.dataset.target);g.inputs[Number(target.dataset.pin)]=from;}else logic.outputs.find(p=>p.name===output.dataset.outputName).source=from;});$('.schematic-hint').textContent='Click an input to toggle · Drag gates to arrange · Click an output pin, then an input pin to connect';return;}
  const input=e.target.closest('[data-input-toggle]');if(input){const name=input.dataset.inputToggle,p=model.logic.inputs.find(p=>p.name===name);state.inputs[name]=((state.inputs[name]||0)+1)%(p.width===32?4294967296:2**p.width);renderSchematic();status(`${name} = ${state.inputs[name]}`);return;}
  const gate=e.target.closest('[data-gate]');if(gate){state.schematicSelection=gate.dataset.gate;state.selection.clear();renderSchematic();}else if(!target){state.schematicSelection=null;renderSchematic();renderInspector();}
});
$('#schematicSvg').addEventListener('pointerdown',e=>{state.preventSchematicClick=false;if(state.busy||e.button!==0||e.target.closest('.port-hit'))return;const g=e.target.closest('[data-gate]');if(!g)return;const p=schematicPoint(e),position=schematicGeometry.positions.get(g.dataset.gate);history.begin(model,'Arrange schematic');state.schematicDrag={id:g.dataset.gate,start:p,position:{...position},moved:false};e.currentTarget.setPointerCapture(e.pointerId);});
$('#schematicSvg').addEventListener('pointermove',e=>{const drag=state.schematicDrag;if(!drag)return;const p=schematicPoint(e);if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>3)drag.moved=true;if(!drag.moved)return;model.logic.positions??={};model.logic.positions[drag.id]={x:drag.position.x+p.x-drag.start.x,y:drag.position.y+p.y-drag.start.y};renderSchematic();});
$('#schematicSvg').addEventListener('pointerup',e=>{const drag=state.schematicDrag;if(!drag)return;state.schematicDrag=null;state.preventSchematicClick=true;state.schematicSelection=drag.id;state.selection.clear();if(history.commit(model))markChanged({edited:false});if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);renderSchematic();});
$('#schematicSvg').addEventListener('pointercancel',()=>{if(state.schematicDrag&&history.pending){model=history.cancel()||model;state.schematicDrag=null;renderSchematic();}});
$('#schematicSvg').addEventListener('wheel',e=>{e.preventDefault();const svg=e.currentTarget,p=schematicPoint(e),b=svg.viewBox.baseVal,factor=Math.exp(e.deltaY*.001);const width=clamp(b.width*factor,180,6000),ratio=width/b.width;svg.setAttribute('viewBox',`${p.x-(p.x-b.x)*ratio} ${p.y-(p.y-b.y)*ratio} ${width} ${b.height*ratio}`);},{passive:false});

function renderWave(){const sim=state.simulation;if(!sim)return;const W=1100,left=188,pad=18,right=W-pad,n=sim.cycles,step=(right-left)/n,rowH=37,header=55,H=header+sim.signals.length*rowH+25;const cursor=clamp(state.cursor,0,n-1);let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" style="height:${H}px" id="waveSvg"><rect width="${W}" height="${H}" fill="#0a151e"/><rect width="${left-1}" height="${H}" fill="#12212c"/><path d="M${left-1} 0 V${H}" stroke="#2e4758"/><text x="16" y="23" fill="#63869b" font-size="9">SIGNAL</text><text x="${left-15}" y="23" fill="#63869b" font-size="9" text-anchor="end">VALUE</text><text x="${left+8}" y="15" fill="#507287" font-size="8">SAMPLE INDEX</text>`;
  const tick=Math.max(1,n/16);for(let t=0;t<=n;t+=tick){const x=left+t*step;svg+=`<path d="M${x} 29 V${H}" stroke="#203747" stroke-width=".8"/><text x="${x+4}" y="38" fill="#638598" font-size="9">${t}</text>`;}
  sim.signals.forEach((signal,i)=>{const y=header+i*rowH;const value=signal.values[cursor],color=signal.kind==='input'?'#76b4ba':'#97c99c';svg+=`<path d="M0 ${y+rowH-1} H${W}" stroke="#1b303e" stroke-width=".7"/><rect x="10" y="${y+13}" width="5" height="5" rx="1" fill="${color}"/><text x="25" y="${y+19}" fill="#a0bdcc" font-size="10">${esc(signal.name)}${signal.width>1?` [${signal.width-1}:0]`:''}</text><text x="${left-16}" y="${y+19}" fill="${color}" font-size="10" text-anchor="end">${value===null?'X':signal.width>1?'0x'+value.toString(16):value}</text>`;
    if(signal.width===1){let path='';for(let t=0;t<n;t++){const x=left+t*step,yy=y+(signal.values[t]?7:27);path+=`${t?'L':'M'}${x},${yy} H${x+step}`;}svg+=`<path d="${path}" stroke="${color}" stroke-width="1.4" fill="none"/>`;for(let t=0;t<n;t++)if(signal.values[t])svg+=`<rect x="${left+t*step}" y="${y+7}" width="${step}" height="20" fill="${color}" opacity=".06"/>`;}
    else{let start=0;while(start<n){let end=start+1;while(end<n&&signal.values[end]===signal.values[start])end++;const x=left+start*step,xx=left+end*step,slant=Math.min(3,(xx-x)/3);svg+=`<path d="M${x} ${y+17} L${x+slant} ${y+7} H${xx-slant} L${xx} ${y+17} L${xx-slant} ${y+27} H${x+slant} Z" fill="${color}" fill-opacity=".04" stroke="${color}" stroke-width="1"/>`;if(xx-x>24)svg+=`<text x="${(x+xx)/2}" y="${y+21}" text-anchor="middle" fill="${color}" font-size="9">${signal.values[start]===null?'X':signal.values[start].toString(16)}</text>`;start=end;}}
  });
  const x=left+(cursor+.5)*step;svg+=`<path d="M${x} 28 V${H}" stroke="#dcc394" stroke-width="1" stroke-dasharray="3 2"/><path d="M${x-5} 26 H${x+5} L${x} 34 Z" fill="#e0c694"/></svg>`;$('#waveBody').innerHTML=svg;$('#waveCursor').textContent=`Cursor: ${cursor} / ${n-1}`;
}
function cursorFromEvent(e){const svg=$('#waveSvg');if(!svg)return;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());if(q.x<188)return;state.cursor=clamp(Math.floor((q.x-188)/(1100-18-188)*state.simulation.cycles),0,state.simulation.cycles-1);renderWave();}
$('#waveBody').addEventListener('pointerdown',e=>{state.waveDragging=true;$('#waveBody').setPointerCapture(e.pointerId);cursorFromEvent(e);});$('#waveBody').addEventListener('pointermove',e=>{if(state.waveDragging)cursorFromEvent(e);});$('#waveBody').addEventListener('pointerup',()=>{state.waveDragging=false;});$('#sampleCount').addEventListener('change',()=>runTask('simulate'));

function download(name,text,type='text/plain'){const blob=text instanceof Blob?text:new Blob([text],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);status(`Exported ${name}`);}
function exportProject(){download(`${model.name}.silicore`,JSON.stringify({...model,draftHDL:$('#hdlEditor').value},null,2),'application/json');queueSave();toast('Project exported with the design, logic graph, and RTL draft.');}
function exportSVG(){const scene=buildLayoutScene(model,state.layers,{routeOpacity:.6,cellLabels:state.cellLabels});const d=model.die;let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${d.x-30} ${d.y-50} ${d.w+60} ${d.h+110}" width="${d.w+60}" height="${d.h+110}"><title>${esc(model.name)} — Silicore Studio</title><rect x="${d.x-30}" y="${d.y-50}" width="${d.w+60}" height="${d.h+110}" fill="#080d11"/>`;svg+=scene.items.map(r=>`<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" fill="${r.color}" opacity="${r.alpha}"/>`).join('');svg+=scene.labels.map(l=>`<text x="${l.x}" y="${l.y}" fill="${l.color||'#b9cbd7'}" font-family="${l.mono?'monospace':'sans-serif'}" font-size="${l.size||l.screenSize||14}" text-anchor="${l.align==='center'?'middle':l.align==='right'?'end':'start'}" dominant-baseline="middle">${esc(l.text)}</text>`).join('');svg+='</svg>';download(`${model.name}.svg`,svg,'image/svg+xml');}
function exportVCD(){const sim=state.simulation;const encode=i=>{let s='';do{s=String.fromCharCode(33+i%94)+s;i=Math.floor(i/94)-1;}while(i>=0);return s;};const ids=sim.signals.map((_,i)=>encode(i));let text=`$date ${new Date().toISOString()} $end\n$version Silicore ${VERSION} $end\n$comment Combinational two-state samples. A 1 ns sample spacing is assigned for VCD interchange; no propagation or sequential simulation. $end\n$timescale 1ns $end\n$scope module ${model.logic.name} $end\n${sim.signals.map((s,i)=>`$var wire ${s.width} ${ids[i]} ${s.name} $end`).join('\n')}\n$upscope $end\n$enddefinitions $end\n`;
  for(let t=0;t<sim.cycles;t++){text+=`#${t}\n`;for(let i=0;i<sim.signals.length;i++){const s=sim.signals[i];if(t&&s.values[t]===s.values[t-1])continue;const v=s.values[t];text+=s.width===1?`${v===null?'x':v}${ids[i]}\n`:`b${v===null?'x'.repeat(s.width):v.toString(2).padStart(s.width,'0')} ${ids[i]}\n`;}}
  download(`${model.logic.name}.vcd`,text);toast(`Exported ${sim.signals.length} traces to VCD.`);
}
async function importFile(file){if(!file)return;if(state.busy){toast('Finish the running task before importing.');return;}if(file.size>32*1024*1024)throw new Error('Import is limited to 32 MB');const text=await file.text();
  if(/\.(v|sv)$/i.test(file.name)){setView('rtl');syncEditor(text);await runTask('compile');return;}
  if(/\.def$/i.test(file.name)){const result=importDEFPlacement(text,model);transact('Import DEF placement',()=>{model=result.model;});fit();toast(`Imported ${result.count} matching component placements.`);return;}
  const data=JSON.parse(text),parsed=validateProject(data);transact('Import project',()=>{model=parsed;});state.inputs={};state.schematicSelection=null;state.timing=analyzeTiming(model);state.checks=checkDesign(model);state.timingStale=false;state.checksStale=false;state.simulation=simulate(model.logic);refreshAll();if(typeof data.draftHDL==='string'&&data.draftHDL.length<=1000000)syncEditor(data.draftHDL);fit();log('success',`Imported ${model.name}: ${fmt(model.cells.length)} objects.`);queueSave();toast(`Opened ${model.name}`);
}
$('#fileInput').addEventListener('change',async e=>{try{await importFile(e.target.files[0]);}catch(error){handleError(error);}e.target.value='';});
document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();importFile(e.dataTransfer.files[0]).catch(handleError);}});
function modal(title,html){$('#modalTitle').textContent=title;$('#modalContent').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function showHelp(){modal('Silicore Studio',`<p>A local-first electronic design workbench with a real editable database, a retained WebGPU layout renderer, and CPU worker-based implementation tools.</p><h3>Navigate & edit</h3><div class="shortcut-grid">${[['Select / move','V'],['Pan','H / Space'],['Connect cells','R'],['Draw macro','B'],['Measure','D'],['Fit design','F'],['Undo','Ctrl/⌘ Z'],['Redo','Ctrl/⌘ ⇧ Z'],['Duplicate','Ctrl/⌘ D'],['Save project','Ctrl/⌘ S'],['Command palette','Ctrl/⌘ K'],['Delete selection','Delete']].map(([a,b])=>`<div><span>${a}</span><kbd>${b}</kbd></div>`).join('')}</div><h3>Layout</h3><p>Wheel to zoom around the pointer. Drag to select an area. Hold Shift to extend selection. Unlock fixed macros in Properties, then drag a corner to resize. Double-click a mapped control cell to cross-probe its schematic.</p><h3>RTL & schematic</h3><p>The Verilog subset supports unsigned scalar and 1–32 bit buses, continuous assignments, bitwise/Boolean operators, addition/subtraction, equality, ternary selection, and constant bit selects. Click schematic inputs to toggle values; connect output pins to input pins to edit logic.</p><h3>Scope</h3><p>This is an independent functional prototype, not Synopsys software or a full EDA suite. The reference floorplan is synthetic; only its control_unit is mapped to the editable RTL. No sequential HDL, analog simulation, full SystemVerilog, technology mapping, foundry rules, LVS, extraction, GDSII, or signoff.</p><div class="modal-actions"><button class="primary-button" data-action="closeModal">Start designing</button></div>`);}
function showSettings(){modal('Workspace settings',`<div class="setting-row"><span>Clock period <small class="muted">(estimated timing)</small></span><input id="settingClock" type="number" value="${model.clock}" min="0.001" max="10000" step="0.1"></div><div class="setting-row"><span>Snap placement to 1 µm</span><input type="checkbox" id="settingSnap" ${state.snap?'checked':''}></div><div class="setting-row"><span>Cell labels at high zoom</span><input type="checkbox" id="settingLabels" ${state.cellLabels?'checked':''}></div><div class="setting-row"><span>Route visibility</span><input type="range" id="settingOpacity" min="0" max="1" step="0.05" value="${state.routeOpacity}"></div><div class="setting-row"><span>Active renderer</span><strong>${esc(renderer.backend)}</strong></div><div class="setting-row"><span>Retained geometry</span><span>${fmt(renderer.primitiveCount)} instances</span></div><div class="setting-row"><span>Execution</span><span>Dedicated module worker</span></div><p style="margin-top:16px;font-size:10px">The display uses a synthetic demonstration library. Timing is computed from per-cell delays and Manhattan wire length; it is not a static-timing signoff engine.</p>${renderer.error?`<p class="inspector-note">Renderer diagnostic: ${esc(renderer.error)}</p>`:''}<div class="modal-actions">${renderer.backend==='WebGPU'?'<button class="small-button" data-action="canvasFallback">Use Canvas 2D</button>':''}<button class="primary-button" data-action="applySettings">Apply settings</button></div>`);}
function applySettings(){const clock=Number($('#settingClock').value);if(!Number.isFinite(clock)||clock<.001||clock>10000){toast('Clock period must be between 0.001 and 10,000 ns.',true);return;}const snap=$('#settingSnap').checked,labels=$('#settingLabels').checked,opacity=Number($('#settingOpacity').value);if(clock!==model.clock)transact('Update clock constraint',()=>{model.clock=clock;});state.snap=snap;state.cellLabels=labels;state.routeOpacity=opacity;$('#snapButton').classList.toggle('active',state.snap);refreshScene();$('#modal').close();status('Workspace settings updated');}
function showAddGate(){modal('Add logic node',`<p>Select a primitive from the synthetic library. The new node uses the first module inputs. Rewire its pins to integrate it into the design.</p><div class="lib-grid" style="grid-template-columns:repeat(4,1fr)">${['AND','OR','XOR','NOT','NAND','NOR','BUF','MUX','ADD','SUB','EQ','NE'].map(type=>`<button class="library-cell" data-add-gate="${type}">${icon('schematic')}<span>${type}</span><small>${LIBRARY[type].arity} inputs</small></button>`).join('')}</div>`);}
function newDemo(){modal('Open reference design',`<p>Replace the current workspace with the Aurora reference floorplan? The current project can be exported first. Undo remains available after replacement.</p><div class="modal-actions"><button class="small-button" data-action="save">Export current project</button><button class="primary-button" data-action="confirmNew">Open reference design</button></div>`);}
function confirmNew(){if(state.busy)return;transact('Open reference design',()=>{model=createDemo();});state.inputs={req:1,ready:0,enable:1,reset_n:1,mode:0};state.schematicSelection=null;state.timing=analyzeTiming(model);state.checks=checkDesign(model);state.timingStale=false;state.checksStale=false;state.simulation=simulate(model.logic);state.flow={import:'done',place:'done',route:'preview',timing:'estimated',check:'done'};refreshAll();$('#modal').close();setView('layout');fit();queueSave();toast('Aurora reference design opened.');}
const commands=[
  {name:'Run implementation flow',action:'flow',key:'',icon:'play'},
  {name:'Fit design in viewport',action:'fit',key:'F',icon:'fit'},
  {name:'Synthesize Verilog RTL',action:'synthesize',key:'Ctrl+Enter',icon:'code'},
  {name:'Place and legalize cells',action:'place',icon:'grid'},
  {name:'Route nets around macros',action:'route',icon:'route'},
  {name:'Estimate timing paths',action:'timing',icon:'time'},
  {name:'Run geometric design checks',action:'check',icon:'checks'},
  {name:'Run logic simulation',action:'simulate',icon:'wave'},
  {name:'Save project to file',action:'save',key:'Ctrl+S',icon:'save'},
  {name:'Import project, RTL, or DEF placement',action:'import',icon:'upload'},
  {name:'Export SVG layout',action:'exportSVG',icon:'download'},
  {name:'Export DEF placement',action:'exportDEF',icon:'download'},
  {name:'Export VCD waveforms',action:'exportVCD',icon:'wave'},
  {name:'Open physical design',view:'layout',icon:'chip'},
  {name:'Open logic schematic',view:'schematic',icon:'schematic'},
  {name:'Open RTL editor',view:'rtl',icon:'code'},
  {name:'Open waveforms',view:'wave',icon:'wave'},
  {name:'Workspace settings',action:'settings',icon:'settings'},
  {name:'Keyboard shortcuts and scope',action:'help',icon:'help'},
];
let paletteItems=[],paletteIndex=0;
function showPalette(){const el=$('#palette');if(!el.open)el.showModal();$('#paletteInput').value='';paletteIndex=0;renderPalette();$('#paletteInput').focus();}
function renderPalette(){const q=$('#paletteInput').value.trim().toLowerCase();paletteItems=commands.filter(c=>c.name.toLowerCase().includes(q));if(q){paletteItems.push(...model.cells.filter(c=>`${c.name} ${c.ref}`.toLowerCase().includes(q)).slice(0,20).map(c=>({name:c.name,cell:c.id,icon:c.kind==='macro'?'box':'chip',key:c.ref})));paletteItems.push(...model.nets.filter(n=>n.name.toLowerCase().includes(q)).slice(0,8).map(n=>({name:n.name,net:n.id,icon:'route',key:'Net'})));}paletteItems=paletteItems.slice(0,30);paletteIndex=clamp(paletteIndex,0,Math.max(0,paletteItems.length-1));$('#paletteResults').innerHTML=paletteItems.length?paletteItems.map((c,i)=>`<button class="palette-result ${i===paletteIndex?'selected':''}" data-palette-index="${i}">${icon(c.icon)}<span>${esc(c.name)}</span><small>${esc(c.key||'')}</small></button>`).join(''):'<div class="tree-empty">No matching commands or design objects</div>';$('#paletteResults .selected')?.scrollIntoView({block:'nearest'});}
function choosePalette(index){const item=paletteItems[index];if(!item)return;$('#palette').close();if(item.action)invoke(item.action);else if(item.view)setView(item.view);else if(item.cell)selectCells([item.cell],{focus:true});else if(item.net)selectNet(item.net);}
$('#paletteInput').addEventListener('input',()=>{paletteIndex=0;renderPalette();});$('#paletteInput').addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();paletteIndex=clamp(paletteIndex+(e.key==='ArrowDown'?1:-1),0,paletteItems.length-1);renderPalette();}else if(e.key==='Enter'){e.preventDefault();choosePalette(paletteIndex);}});
const menus={
 File:[['Open reference design','new'],['Import project / HDL / placement','import','Ctrl+O'],['Save project','save','Ctrl+S'],null,['Export layout as SVG','exportSVG'],['Export placement as DEF','exportDEF'],['Export Verilog source','exportHDL'],['Export waveform VCD','exportVCD']],
 Edit:[['Undo','undo','Ctrl+Z'],['Redo','redo','Ctrl+Shift+Z'],null,['Select all instances','selectAll','Ctrl+A'],['Duplicate selection','duplicate','Ctrl+D'],['Delete selection','delete','Delete']],
 View:[['Fit entire design','fit','F'],['Zoom in','zoomIn','+'],['Zoom out','zoomOut','−'],null,['Toggle navigator','panels'],['Focus workspace','maximize'],['Toggle analysis panel','console'],['Toggle placement grid','grid'],['Show cell labels at high zoom','labels']],
 Design:[['Synthesize RTL','synthesize','Ctrl+Enter'],['Place and legalize','place'],['Global route','route'],['Estimate timing','timing'],['Check design geometry','check'],null,['Run implementation flow','flow']],
 Tools:[['Command palette','palette','Ctrl+K'],['Measure distance','measureTool','D'],['Clear measurement','clearMeasure'],['Workspace settings','settings']],
};
function showMenu(name,button){const items=menus[name];if(!items)return;const popup=$('#menuPopup');if(!popup.hidden&&popup.dataset.name===name){popup.hidden=true;return;}popup.dataset.name=name;popup.innerHTML=items.map(item=>item?`<button data-action="${item[1]}"><span>${item[0]}</span>${item[2]?`<kbd>${item[2]}</kbd>`:''}</button>`:'<div class="menu-separator"></div>').join('');const rect=button.getBoundingClientRect();popup.style.left=`${Math.min(rect.left,window.innerWidth-270)}px`;popup.style.top=`${rect.bottom+3}px`;popup.hidden=false;}
function selectNet(id){const n=model.nets.find(n=>n.id===id);if(!n)return;selectCells([n.from,...n.to],{focus:true});state.selectedNet=id;renderer.invalidate();status(`${n.name} · ${n.to.length} sink${n.to.length===1?'':'s'}`);}
const actions={
  flow:runFlow,place:()=>runTask('place'),route:()=>runTask('route'),timing:()=>runTask('timing'),check:()=>runTask('check'),synthesize:()=>runTask('compile'),simulate:()=>runTask('simulate'),
  fit,zoomIn:()=>zoom(1.25),zoomOut:()=>zoom(.8),undo:()=>undo(),redo:()=>undo(true),delete:deleteSelected,duplicate,
  selectAll:()=>{setView('layout');selectCells(model.cells.map(c=>c.id));},deselect:()=>{state.schematicSelection=null;selectCells([]);if(state.view==='schematic')renderSchematic();},
  focusSelected:()=>selectCells([...state.selection],{focus:true}),
  save:exportProject,import:()=>$('#fileInput').click(),exportSVG,exportDEF:()=>download(`${model.name}.def`,exportDEF(model)),exportHDL:()=>download(`${model.logic.name}.v`,$('#hdlEditor').value),exportVCD,
  new:newDemo,confirmNew,help:showHelp,settings:showSettings,applySettings,closeModal:()=>$('#modal').close(),palette:showPalette,
  snap:()=>{state.snap=!state.snap;$('#snapButton').classList.toggle('active',state.snap);status(`Placement snapping ${state.snap?'enabled':'disabled'}`);},
  grid:()=>{const layer=state.layers.find(l=>l.id==='grid');layer.visible=!layer.visible;renderLayers();refreshScene();},
  allLayers:()=>{const value=!state.layers.every(l=>l.visible);state.layers.forEach(l=>l.visible=value);renderLayers();refreshScene();},
  labels:()=>{state.cellLabels=!state.cellLabels;refreshScene();toast(`High-zoom cell labels ${state.cellLabels?'enabled':'disabled'}.`);},
  panels:()=>{document.body.classList.toggle('navigator-hidden');renderer.resize();},maximize:()=>{document.body.classList.toggle('focus-mode');renderer.resize();},
  console:()=>{document.body.classList.toggle('console-hidden');renderer.resize();},clearConsole:()=>{state.logs=[];renderLogs();},
  measureTool:()=>setTool('measure'),clearMeasure:()=>{state.measure=null;renderer.invalidate();},
  addGate:showAddGate,crossProbe:()=>{const c=model.cells.find(c=>c.logicId===state.schematicSelection);if(c)selectCells([c.id],{focus:true});else toast('This logic node has no mapped physical cell.');},
  step:()=>{state.cursor=(state.cursor+1)%state.simulation.cycles;renderWave();},resetSim:()=>{state.cursor=0;renderWave();},
  canvasFallback:()=>{renderer.fallback();renderer.resize();$('#modal').close();toast('Switched to Canvas 2D. Reload to retry WebGPU.');},
};
function invoke(action){const fn=actions[action];if(!fn){log('error',`Unknown action: ${action}`);return;}try{Promise.resolve(fn()).catch(handleError);}catch(e){handleError(e);}}
document.addEventListener('click',e=>{
  const button=e.target.closest('button,[data-action]');const popup=$('#menuPopup');
  if(button?.dataset.menu){showMenu(button.dataset.menu,button);return;}if(!e.target.closest('#menuPopup'))popup.hidden=true;
  if(button?.dataset.action){popup.hidden=true;invoke(button.dataset.action);return;}
  if(button?.dataset.view){setView(button.dataset.view);return;}if(button?.dataset.tool){setTool(button.dataset.tool);return;}if(button?.dataset.mode){setMode(button.dataset.mode);return;}
  if(button?.dataset.bottom){setBottom(button.dataset.bottom);return;}if(button?.dataset.lefttab){state.leftTab=button.dataset.lefttab;$$('[data-lefttab]').forEach(b=>b.classList.toggle('active',b===button));renderTree();return;}
  if(button?.dataset.expand){const id=button.dataset.expand;state.expanded.has(id)?state.expanded.delete(id):state.expanded.add(id);renderTree();return;}
  if(button?.dataset.cell){selectCells([button.dataset.cell],{focus:true,extend:e.shiftKey});return;}
  if(button?.dataset.insert){insertCell(button.dataset.insert);return;}if(button?.dataset.addGate){$('#modal').close();setView('schematic');addLogicGate(button.dataset.addGate);return;}
  if(button?.dataset.net){selectNet(button.dataset.net);return;}if(button?.dataset.paletteIndex!==undefined){choosePalette(Number(button.dataset.paletteIndex));return;}
  const path=e.target.closest('[data-path]');if(path){const p=state.timing.paths[Number(path.dataset.path)];selectCells(p.ids,{focus:true});state.mode='timing';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='timing'));renderer.invalidate();status(`Critical path: ${p.ids.length} stages · slack ${fmt(p.slack,3)} ns`);}
  const issue=e.target.closest('[data-issue]');if(issue){const p=state.checks.issues[Number(issue.dataset.issue)];selectCells(p.ids,{focus:true});status(`${p.rule}: ${p.message}`);}
});
document.addEventListener('change',e=>{
  const el=e.target;if(el.dataset.layer){const layer=state.layers.find(l=>l.id===el.dataset.layer);layer.visible=el.checked;$('#layerCount').textContent=state.layers.filter(l=>l.visible).length;refreshScene();return;}
  if(el.dataset.prop){const c=selectedCells()[0];if(!c)return;const k=el.dataset.prop;let value=k==='fixed'?el.checked:k==='name'?el.value:Number(el.value);if(['x','y','w','h'].includes(k)&&(!Number.isFinite(value)||Math.abs(value)>10000||(['w','h'].includes(k)&&value<4))){toast('Invalid geometry value.',true);renderInspector();return;}if(k==='name'&&(!value.trim()||model.cells.some(other=>other.id!==c.id&&other.name===value))){toast('Instance name must be nonempty and unique.',true);renderInspector();return;}transact(`Edit ${k}`,()=>{c[k]=value;}, {reroute:k!=='fixed'&&k!=='name'});return;}
  if(el.id==='gateType'){const type=el.value;editLogic('Change gate type',logic=>{logic.gates.find(g=>g.id===state.schematicSelection).type=type;});}
});
document.addEventListener('dblclick',e=>{const row=e.target.closest('[data-layerrow]');if(row){e.preventDefault();const id=row.dataset.layerrow;state.layers.forEach(l=>l.visible=l.id===id);renderLayers();refreshScene();toast(`Isolated ${state.layers.find(l=>l.id===id).name}`);}});
$('#treeSearch').addEventListener('input',renderTree);

async function executeCommand(command){const [name,...args]=command.trim().split(/\s+/);if(!name)return;log('command',command);const aliases={report_timing:'timing',check_design:'check',place_design:'place',route_design:'route',synthesize:'synthesize',simulate:'simulate',fit:'fit',clear:'clearConsole',save:'save'};
  if(aliases[name]){invoke(aliases[name]);return;}switch(name){case'help':log('info','Commands: report_timing, check_design, place_design, route_design, synthesize, simulate, fit, select <name>, set_clock <ns>, set_layer <M1|M2|…> <on|off>, save, clear.');break;
    case'select':{const term=args.join(' ').toLowerCase();if(!term)throw new Error('Usage: select <instance name or fragment>');const cells=model.cells.filter(c=>c.name.toLowerCase().includes(term));if(!cells.length)throw new Error(`No instances match '${term}'`);selectCells(cells.map(c=>c.id),{focus:true});log('info',`Selected ${cells.length} instances.`);break;}
    case'set_clock':{const clock=Number(args[0]);if(!Number.isFinite(clock)||clock<.001||clock>10000)throw new Error('Usage: set_clock <period in ns, 0.001–10000>');transact('Set clock period',()=>{model.clock=clock;});log('success',`Clock period set to ${clock} ns. Run report_timing to update analysis.`);break;}
    case'set_layer':{const layer=state.layers.find(l=>l.id.toLowerCase()===args[0]?.toLowerCase());if(!layer||!['on','off'].includes(args[1]))throw new Error('Usage: set_layer <layer> <on|off>');layer.visible=args[1]==='on';renderLayers();refreshScene();break;}
    default:throw new Error(`Unknown command '${name}'. Type help. The console is not a Tcl interpreter.`);
  }
}
$('#commandForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#commandInput'),command=input.value.trim();if(!command)return;commandHistory.push(command);commandHistoryIndex=commandHistory.length;input.value='';executeCommand(command).catch(handleError);});
$('#commandInput').addEventListener('keydown',e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();commandHistoryIndex=clamp(commandHistoryIndex+(e.key==='ArrowUp'?-1:1),0,commandHistory.length);e.target.value=commandHistory[commandHistoryIndex]||'';}});
document.addEventListener('keydown',e=>{
  const editing=e.target.matches('input,textarea,select,[contenteditable=true]');const mod=e.ctrlKey||e.metaKey;
  if(e.key==='Escape'){state.wireStart=null;state.routeStart=null;state.measure=null;$('#menuPopup').hidden=true;setHint('');if(history.pending&&state.pointer){model=history.cancel()||model;state.pointer=null;refreshAll();}renderer.invalidate();return;}
  if(mod&&e.key.toLowerCase()==='k'){e.preventDefault();showPalette();return;}if($('#modal').open||$('#palette').open)return;
  if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();exportProject();return;}if(mod&&e.key.toLowerCase()==='o'){e.preventDefault();$('#fileInput').click();return;}
  if(editing)return;
  if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();undo(true);return;}
  if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();return;}if(mod&&e.key.toLowerCase()==='a'){e.preventDefault();actions.selectAll();return;}
  if(e.code==='Space'){e.preventDefault();state.space=true;surface.style.cursor='grab';return;}
  const map={v:'select',h:'hand',r:'route',b:'macro',d:'measure'};const key=e.key.toLowerCase();if(map[key]){setTool(map[key]);return;}if(key==='f')fit();else if(['Delete','Backspace'].includes(e.key)){e.preventDefault();deleteSelected();}else if(e.key==='+'||e.key==='=')zoom(1.25);else if(e.key==='-')zoom(.8);else if(e.key==='/'){e.preventDefault();$('#treeSearch').focus();}else if(e.key==='`'){e.preventDefault();setBottom('console');$('#commandInput').focus();}
});
document.addEventListener('keyup',e=>{if(e.code==='Space'){state.space=false;surface.style.cursor=state.tool==='hand'?'grab':'default';}});window.addEventListener('blur',()=>{state.space=false;});
window.addEventListener('beforeunload',()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(model));localStorage.setItem('silicore:hdl-draft',$('#hdlEditor').value);}catch{}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();}});

state.inputs={req:1,ready:0,enable:1,reset_n:1,mode:0};
renderTree();renderLayers();renderInspector();renderFlow();renderReports();syncEditor(draft||model.hdl);refreshScene();
log('info',restoreMessage||'Opened Aurora reference design from the built-in fixture.');
log('success',`Loaded ${fmt(designStats(model).cells)} standard cells, ${designStats(model).macros} macros, and ${fmt(model.nets.length)} signal nets.`);
log('success',`Elaborated control_unit · ${model.logic.gates.length} combinational logic nodes.`);
log('info','Synthetic technology library · exploratory timing · geometric checks only.');
const preference=new URLSearchParams(location.search).get('renderer')==='canvas'?'canvas':'auto';
renderer.initialize(preference).then(()=>{fit();status('Ready · select an instance to inspect its properties');$('#saveStatus').innerHTML='<span class="small-dot"></span> Local workspace';}).catch(handleError);
// A narrow diagnostics surface for tests and integrations; model snapshots cannot mutate live state.
window.Silicore=Object.freeze({version:VERSION,getSnapshot:()=>clone(model),getState:()=>({view:state.view,selection:[...state.selection],busy:state.busy,backend:renderer.backend,rendererError:renderer.error||null,primitiveCount:renderer.primitiveCount,wns:state.timing.wns,checks:state.checks.issues.length,cursor:state.cursor,history:{undo:history.undoStack.length,redo:history.redoStack.length}}),worldToScreen:(x,y)=>renderer.camera.worldToScreen(x,y),runTask,fit,evaluate:values=>evaluateLogic(model.logic,values),dispatch:invoke});
